// GENERATED by sync-math.sh from RentVsBuy/utils/. Do not edit by hand.

// calculator.ts
function rateCalc(nper, pmt, pv, fv_) {
  let r = 5e-3;
  for (let i = 0; i < 300; i++) {
    if (Math.abs(r) < 1e-10) r = 1e-6;
    const pow = Math.pow(1 + r, nper);
    const f = pv * pow + pmt * (pow - 1) / r + fv_;
    const df = pv * nper * Math.pow(1 + r, nper - 1) + pmt * (nper * Math.pow(1 + r, nper - 1) * r - (pow - 1)) / (r * r);
    if (Math.abs(df) < 1e-14) break;
    const rNext = r - f / df;
    if (Math.abs(rNext - r) < 1e-12) return rNext;
    r = Math.min(Math.max(rNext, -0.9), 5);
  }
  return r;
}
function fv(rate, nper, pmt, pv = 0) {
  if (Math.abs(rate) < 1e-10) return -pv - pmt * nper;
  const pow = Math.pow(1 + rate, nper);
  return -pv * pow - pmt * (pow - 1) / rate;
}
function pmtCalc(rate, nper, pv) {
  if (Math.abs(rate) < 1e-10) return pv / nper;
  return rate * pv / (1 - Math.pow(1 + rate, -nper));
}
function remainingBalance(loan, annualRate, termYears, yearsElapsed) {
  const r = annualRate / 12;
  const n = termYears * 12;
  const m = Math.min(yearsElapsed * 12, n);
  if (Math.abs(r) < 1e-10) return loan * (1 - m / n);
  return loan * (Math.pow(1 + r, n) - Math.pow(1 + r, m)) / (Math.pow(1 + r, n) - 1);
}
var DEFAULT_INPUTS = {
  monthlyRent: 2e3,
  homePrice: 6e5,
  downPaymentPct: 0.2,
  rentAppreciation: 0.03,
  rentersInsuranceAnnual: 100,
  renterUtilities: 200,
  equityReturn: 0.06,
  closingCostsPct: 0.03,
  mortgageRate: 0.055,
  mortgageTerm: 30,
  propertyTaxRate: 0.01,
  hoa: 0,
  appreciation: 0.035,
  homeInsurancePct: 25e-4,
  maintenancePct: 0.01,
  buyerUtilities: 200,
  standardDeduction: 29200,
  taxRate: 0.3,
  pmiRate: 75e-4
};
function calculate(inputs) {
  const downPayment = inputs.homePrice * inputs.downPaymentPct;
  const closingCosts = inputs.homePrice * inputs.closingCostsPct;
  const loanAmount = inputs.homePrice - downPayment;
  const r = inputs.mortgageRate / 12;
  const monthlyMortgage = pmtCalc(r, inputs.mortgageTerm * 12, loanAmount);
  const monthlyPropertyTax = inputs.homePrice * inputs.propertyTaxRate / 12;
  const monthlyHomeInsurance = inputs.homePrice * inputs.homeInsurancePct / 12;
  const monthlyMaintenance = inputs.homePrice * inputs.maintenancePct / 12;
  const monthlyPMI = inputs.downPaymentPct < 0.2 ? loanAmount * inputs.pmiRate / 12 : 0;
  let pmiEndMonth = 0;
  if (monthlyPMI > 0) {
    const target = inputs.homePrice * 0.8;
    for (let m = 1; m <= inputs.mortgageTerm * 12; m++) {
      if (remainingBalance(loanAmount, inputs.mortgageRate, inputs.mortgageTerm, m / 12) <= target) {
        pmiEndMonth = m;
        break;
      }
    }
  }
  const totalMonthlyOwnerCost = monthlyMortgage + monthlyPropertyTax + inputs.hoa + monthlyHomeInsurance + monthlyMaintenance + inputs.buyerUtilities + monthlyPMI;
  const initialInvestment = downPayment + closingCosts;
  const monthlyRenterCost = inputs.monthlyRent + inputs.rentersInsuranceAnnual / 12 + inputs.renterUtilities;
  const monthlyRenterSavings = totalMonthlyOwnerCost - monthlyRenterCost;
  const equityR = inputs.equityReturn / 12;
  const propTaxAnnual = monthlyPropertyTax * 12;
  const periods = [1, 5, 10, 20, 30].map((years) => {
    const renterInitialCompounded = initialInvestment * Math.pow(1 + equityR, years * 12);
    let renterNW = renterInitialCompounded;
    let totalInterestPaid = 0;
    let totalTaxBenefit = 0;
    let investedTaxSavings = 0;
    let ownerInvestedSavings = 0;
    for (let y = 0; y < years; y++) {
      const remainingMonths = (years - y - 1) * 12;
      const rentThisYear = inputs.monthlyRent * Math.pow(1 + inputs.rentAppreciation, y);
      const renterCostThisYear = rentThisYear + inputs.rentersInsuranceAnnual / 12 + inputs.renterUtilities;
      const ownerCostThisYear = pmiEndMonth > 0 && y * 12 >= pmiEndMonth ? totalMonthlyOwnerCost - monthlyPMI : totalMonthlyOwnerCost;
      const monthlySavings = ownerCostThisYear - renterCostThisYear;
      if (monthlySavings > 0) {
        renterNW += fv(equityR, remainingMonths, 0, -fv(equityR, 12, -monthlySavings, 0));
      }
      if (monthlySavings < 0) {
        ownerInvestedSavings += fv(equityR, remainingMonths, 0, -fv(equityR, 12, monthlySavings, 0));
      }
      const interestThisYear = y >= inputs.mortgageTerm ? 0 : monthlyMortgage * 12 - (remainingBalance(loanAmount, inputs.mortgageRate, inputs.mortgageTerm, y) - remainingBalance(loanAmount, inputs.mortgageRate, inputs.mortgageTerm, y + 1));
      totalInterestPaid += interestThisYear;
      const annualTaxBenefit = Math.max(
        0,
        interestThisYear + propTaxAnnual - inputs.standardDeduction
      ) * inputs.taxRate;
      totalTaxBenefit += annualTaxBenefit;
      const monthlyBenefit = annualTaxBenefit / 12;
      investedTaxSavings += fv(equityR, remainingMonths, 0, -fv(equityR, 12, -monthlyBenefit, 0));
    }
    const remaining = remainingBalance(
      loanAmount,
      inputs.mortgageRate,
      inputs.mortgageTerm,
      years
    );
    const homeValue = inputs.homePrice * Math.pow(1 + inputs.appreciation, years);
    const homeEquity = homeValue - remaining;
    const equityFromPrincipal = loanAmount - remaining;
    const equityFromAppreciation = homeValue - inputs.homePrice;
    const buyerNW = homeEquity + investedTaxSavings + ownerInvestedSavings;
    const propTaxPaid = propTaxAnnual * years;
    const itemizedDeductions = totalInterestPaid + propTaxPaid;
    const monthlyTaxBenefit = totalTaxBenefit / (years * 12);
    const breakEvenBase = Math.max(renterNW - investedTaxSavings - ownerInvestedSavings + remaining, 0.01);
    const breakEvenAppreciation = Math.pow(breakEvenBase / inputs.homePrice, 1 / years) - 1;
    const avgRenterCost = inputs.monthlyRent * Math.pow(1 + inputs.rentAppreciation, years / 2) + inputs.rentersInsuranceAnnual / 12 + inputs.renterUtilities;
    const monthlyBreakEvenR = rateCalc(
      years * 12,
      -Math.max(0, totalMonthlyOwnerCost - avgRenterCost),
      -initialInvestment,
      buyerNW
    );
    const renterInvestedSavings = renterNW - renterInitialCompounded;
    return {
      years,
      renterNetWorth: renterNW,
      renterInitialCompounded,
      renterInvestedSavings,
      buyerNetWorth: buyerNW,
      difference: renterNW - buyerNW,
      breakEvenAppreciation,
      homeValue,
      remainingMortgage: remaining,
      equityFromPrincipal,
      equityFromAppreciation,
      homeEquity,
      investedTaxSavings,
      ownerInvestedSavings,
      totalInterestPaid,
      totalPropTaxPaid: propTaxPaid,
      itemizedDeductions,
      taxBenefit: totalTaxBenefit,
      monthlyTaxBenefit,
      breakEvenEquityReturn: monthlyBreakEvenR * 12
    };
  });
  return {
    downPayment,
    closingCosts,
    loanAmount,
    monthlyMortgage,
    monthlyPropertyTax,
    monthlyHomeInsurance,
    monthlyMaintenance,
    monthlyPMI,
    pmiEndMonth,
    totalMonthlyOwnerCost,
    initialInvestment,
    monthlyRenterCost,
    monthlyRenterSavings,
    periods
  };
}

// format.ts
function formatCurrency(value, compact = false) {
  if (!isFinite(value)) return "$\u2014";
  if (compact) {
    const abs = Math.abs(value);
    if (abs >= 1e6) return `${value < 0 ? "-" : ""}$${(abs / 1e6).toFixed(1)}M`;
    if (abs >= 1e3) return `${value < 0 ? "-" : ""}$${(abs / 1e3).toFixed(0)}K`;
  }
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0
  }).format(value);
}
function formatPercent(value, decimals = 1) {
  return `${(value * 100).toFixed(decimals)}%`;
}
function parseInputValue(raw, isPercent) {
  const cleaned = raw.replace(/[$,%\s]/g, "");
  const num = parseFloat(cleaned);
  if (isNaN(num)) return 0;
  return isPercent ? num / 100 : num;
}

// derived.ts
var HORIZONS = [1, 5, 10, 20, 30];
var CHART_YEARS = [0, 5, 10, 15, 20, 25, 30];
var SENS_OFFSETS = [-0.02, -0.01, 0, 0.01, 0.02];
function breakEvenYear(results) {
  const periods = results.periods;
  for (let i = 0; i < periods.length - 1; i++) {
    if (periods[i].difference * periods[i + 1].difference < 0) {
      const t = periods[i].difference / (periods[i].difference - periods[i + 1].difference);
      return {
        year: periods[i].years + t * (periods[i + 1].years - periods[i].years),
        buyingTakesOver: periods[i].difference > 0
      };
    }
  }
  return null;
}
function sensitivityGrid(inputs, horizon) {
  return SENS_OFFSETS.map((appOffset) => {
    const appreciation = Math.max(-0.05, Math.min(0.2, inputs.appreciation + appOffset));
    return {
      appreciation,
      isCurrentApp: appOffset === 0,
      cols: SENS_OFFSETS.map((eqOffset) => {
        const equityReturn = Math.max(0, Math.min(0.3, inputs.equityReturn + eqOffset));
        const res = calculate({ ...inputs, appreciation, equityReturn });
        const p = res.periods.find((x) => x.years === horizon);
        return { equityReturn, isCurrentEq: eqOffset === 0, rentWins: p.difference > 0 };
      })
    };
  });
}
function monthlyCostSeries(inputs, results) {
  const mt = inputs.mortgageTerm;
  const pmiEndYear = results.monthlyPMI > 0 && results.pmiEndMonth > 0 ? results.pmiEndMonth / 12 : null;
  const renter = CHART_YEARS.map((year) => ({
    year,
    cost: inputs.monthlyRent * Math.pow(1 + inputs.rentAppreciation, year) + inputs.rentersInsuranceAnnual / 12 + inputs.renterUtilities
  }));
  const ownerCostAt = (year) => {
    const pmiActive = pmiEndYear !== null && year < pmiEndYear;
    const mortgageDone = year >= mt;
    return (mortgageDone ? 0 : results.monthlyMortgage) + results.monthlyPropertyTax + inputs.hoa + results.monthlyHomeInsurance + results.monthlyMaintenance + inputs.buyerUtilities + (pmiActive ? results.monthlyPMI : 0);
  };
  const years = [...CHART_YEARS];
  if (mt <= 30 && !years.includes(mt)) {
    years.push(mt);
    years.sort((a, b) => a - b);
  }
  const dropYear = Math.min(mt, 30);
  const preDropYear = dropYear - 0.01;
  if (preDropYear > 0) years.splice(years.indexOf(dropYear), 0, preDropYear);
  if (pmiEndYear !== null && pmiEndYear <= 30) {
    const prePmi = pmiEndYear - 0.01;
    if (prePmi > 0) years.push(prePmi);
    years.push(pmiEndYear);
    years.sort((a, b) => a - b);
  }
  const owner = years.map((year) => ({ year, cost: ownerCostAt(year) }));
  let crossoverYear = null;
  for (let i = 0; i < renter.length - 1; i++) {
    const d1 = renter[i].cost - ownerCostAt(renter[i].year);
    const d2 = renter[i + 1].cost - ownerCostAt(renter[i + 1].year);
    if (d1 * d2 < 0) {
      const t = d1 / (d1 - d2);
      crossoverYear = renter[i].year + t * (renter[i + 1].year - renter[i].year);
      break;
    }
  }
  return { renter, owner, crossoverYear };
}
export {
  CHART_YEARS,
  DEFAULT_INPUTS,
  HORIZONS,
  SENS_OFFSETS,
  breakEvenYear,
  calculate,
  formatCurrency,
  formatPercent,
  monthlyCostSeries,
  parseInputValue,
  sensitivityGrid
};
