#!/bin/sh
# Regenerates calculator/calc.js from the iOS app's calculation code.
#
# The math is the one part of this that must never be reimplemented: it is a
# Newton-Raphson RATE solver plus amortisation, and a second copy would drift
# without anyone noticing for a year. The app owns it; this script compiles it
# for the browser. Run after touching utils/calculator.ts or utils/format.ts
# in the app, then commit the regenerated file.
set -e
APP="$HOME/Developer/apps/RentVsBuy"
OUT="$(dirname "$0")/calculator/calc.js"

[ -d "$APP" ] || { echo "App repo not found at $APP"; exit 1; }

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
cat > "$TMP/entry.ts" <<'TS'
export * from './calculator';
export * from './format';
export * from './derived';
TS
cp "$APP/utils/calculator.ts" "$APP/utils/format.ts" "$APP/utils/derived.ts" "$TMP/"

npx --yes esbuild "$TMP/entry.ts" \
  --bundle --format=esm --target=es2020 --platform=browser \
  --banner:js="// GENERATED by sync-math.sh from RentVsBuy/utils/. Do not edit by hand." \
  --outfile="$OUT"

# esbuild stamps each section with the source path it saw, which is a temp
# directory here and changes every run. Rewrite to bare filenames so the file
# is stable and reviewable in a diff.
sed -i '' -E 's|^// .*/([A-Za-z0-9_.-]+\.ts)$|// \1|' "$OUT"

echo "wrote $OUT"
